### ISSUE TITLE
Fetch county short name(ex: IN) and flag links from Country code(ex: +91) and update user table

### ISSUE THREAD

**Issue by prasadpilla** [coronagoapp/solocoin-backend#29]
We currently have country_code field on User model, which is being updated with country short name (ex: IN) through a callback.

Create a new field called "country_short_name" and update it into that.

We have country code (ex: +91) coming into mobile login/signup endpoints, update country_code field from this info.

Also figure out a way to send correct country flag links(CDN or asset pipeline) to frontend.

**Comment by prasadpilla** [comment]
@nronas Also explore if we can just get country short name(ex: IN) from the short code we already have. This might be more reliable than reverse geo coding

**Comment by nronas** [comment]
For posterity, we discussed this in https://discordapp.com/channels/691926147029663805/691926279091650560/695019444170129469 and we are going to add a new field for country name on user and populate it as part of the existing geocoding callback
